# Generated by Django 4.2.13 on 2024-05-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_status_alter_product_image_product_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name_brand',
            new_name='brand_name',
        ),
    ]
