# Generated by Django 4.2.13 on 2024-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_options_alter_brand_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(choices=[('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('HP', 'HP')], max_length=100, verbose_name='نام برند'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
