# Generated by Django 4.2.13 on 2024-05-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='name',
        ),
    ]
