# Generated by Django 4.2.13 on 2024-05-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_brand_name_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_name', to='products.brand', verbose_name='نام برند'),
        ),
    ]
