# Generated by Django 4.2.13 on 2024-06-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product', verbose_name='محصول'),
        ),
    ]
