# Generated by Django 4.2.13 on 2024-06-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_featureproduct_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'وضعیت سفارش', 'verbose_name_plural': 'وضعیت سفارشات'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='products.product', verbose_name='محصصول'),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.product'),
        ),
        migrations.AlterModelTable(
            name='status',
            table='t_status',
        ),
    ]
