# Generated by Django 4.2.13 on 2024-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_status_options_alter_comment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='کاربر', max_length=100, verbose_name='نام'),
        ),
    ]
