# Generated by Django 4.2.13 on 2024-06-14 15:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100, verbose_name='نام'),
        ),
    ]
