# Generated by Django 5.0.2 on 2024-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='کاربر', max_length=100, null=True, verbose_name='نام'),
        ),
    ]
