# Generated by Django 5.0.2 on 2024-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
    ]
